#!/bin/bash
set -eu
shopt -s nocaseglob

cache="$HOME/.cache"
repo="https://github.com/github/gitignore"
repo_dir="$cache/gitignore"

if [ $# -eq 0 ] || [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
    echo 'Usage:   gitignore [language...]'
    echo 'Example: gitignore python node > .gitignore'
    echo 'gitignore by Jerko Steiner <jeremija>'
    echo 'https://github.com/jeremija/gitignore'
    exit
fi

mkdir -p "$cache"

if [ ! -d "$repo_dir" ]; then
    echo Cloning gitignore definitions...
    git clone --depth 1 $repo "$repo_dir"
fi

cd "$repo_dir"

if [ "$1" == "-u" ] || [ "$1" == "--update" ]; then
    git pull
    echo Updated.
    exit
fi

# search for .gitignore files
files="-iname $1.gitignore"
shift
for arg in "$@"; do
    files="$files -o -iname $arg.gitignore"
done
echo $files

for file in $(find . $files); do
    echo "### $file ###"
    cat "$file"
done
